[package]
name = "rust_src"
version = "0.1.0"
authors = ["erwin maruli <erwinmaruli@live.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
